import React from "react";
import Head from 'next/head';

export default function index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>Welcome</h1>
      </div>
    </>
  );
}